### ISSUE TITLE
Race between handshakeHandler and messageHandler

### ISSUE THREAD

**Issue by telackey** [dxos/protocol#9]
This was first encountered in replication like this:

```
console.warn ../../../protocol/packages/protocol-plugin-replicator/dist/replicator.js:154
    Replicate feeds error TypeError: Cannot read property 'replicate' of undefined
        at Replicator._callee6$ (/Users/telackey/Documents/BPI/wireline/protocol/packages/protocol-plugin-replicator/dist/replicator.js:384:22)
        at tryCatch (/Users/telackey/Documents/BPI/wireline/protocol/node_modules/regenerator-runtime/runtime.js:45:40)
        at Generator.invoke [as _invoke] (/Users/telackey/Documents/BPI/wireline/protocol/node_modules/regenerator-runtime/runtime.js:274:22)
        at Generator.prototype.<computed> [as next] (/Users/telackey/Documents/BPI/wireline/protocol/node_modules/regenerator-runtime/runtime.js:97:21)
        at asyncGeneratorStep (/Users/telackey/Documents/BPI/wireline/protocol/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
        at _next (/Users/telackey/Documents/BPI/wireline/protocol/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The messageHandler (in this case, share-feeds) can get triggered before the handshakeHandler has completed.  Since, in this case, the handshakeHandler is what creates the Peer object and adds it to the map, naturally the messageHandler cannot locate the Peer yet.

In the above case, I induced the error by adding a sleep of random duration in the Replicator's onHandshake handler before `this._peers.set`, but in practice I ran into this when there were other plugins (eg, AuthPlugin) ahead of the Replicator, and so working looping and awaiting on all the handshakeHandlers took some time (even if not much time), or because they were async, could yield to other code.

Even though the replication still works in this instance (it updates fine later), there is still a problem, as the implied contract is a strict sequence (first handshake, then messages, etc.) but in practice this is not enforced.

If that is OK, we should make the explicit, and if that is not OK, we should enforce that the handshake is completed before other events are processed.

**Comment by telackey** [comment]
Put another way, should plugins (like Replicator) expect to cope with events in any order.  If that is the case, this is an expected condition and we should remove the warning in Replicator.

If not, and handshake is expected first, then we need to enforce that, and make any attempt to handle some other event before the handshake has completed an error.

**Comment by dboreham** [comment]
I see this as a message emitted running the data-client client test (although the test still passes):

```
(node:732) ExperimentalWarning: queueMicrotask() is experimental.
  console.warn ../../node_modules/@dxos/protocol-plugin-replicator/dist/replicator.js:157
    Replicate feeds error TypeError: Cannot read property 'replicate' of undefined
        at Replicator._replicateHandler (C:\cygwin64\home\david\projects\wireline\incubator\node_modules\@dxos\protocol-plugin-replicator\src\replicator.js:133:12)
        at processTicksAndRejections (internal/process/next_tick.js:81:5)
        at runNextTicks (internal/process/next_tick.js:51:3)
        at processImmediate (timers.js:611:7)

  console.warn ../../node_modules/@dxos/protocol-plugin-replicator/dist/replicator.js:157
    Replicate feeds error TypeError: Cannot read property 'replicate' of undefined
        at Replicator._replicateHandler (C:\cygwin64\home\david\projects\wireline\incubator\node_modules\@dxos\protocol-plugin-replicator\src\replicator.js:133:12)
        at processTicksAndRejections (internal/process/next_tick.js:81:5)
        at runNextTicks (internal/process/next_tick.js:51:3)
        at processImmediate (timers.js:611:7)

  console.warn ../../node_modules/@dxos/protocol-plugin-replicator/dist/replicator.js:157
    Replicate feeds error TypeError: Cannot read property 'replicate' of undefined
        at Replicator._replicateHandler (C:\cygwin64\home\david\projects\wireline\incubator\node_modules\@dxos\protocol-plugin-replicator\src\replicator.js:133:12)
        at processTicksAndRejections (internal/process/next_tick.js:81:5)
        at runNextTicks (internal/process/next_tick.js:51:3)
        at processImmediate (timers.js:611:7)

  console.warn ../../node_modules/@dxos/protocol-plugin-replicator/dist/replicator.js:157
    Replicate feeds error TypeError: Cannot read property 'replicate' of undefined
        at Replicator._replicateHandler (C:\cygwin64\home\david\projects\wireline\incubator\node_modules\@dxos\protocol-plugin-replicator\src\replicator.js:133:12)
        at processTicksAndRejections (internal/process/next_tick.js:81:5)
        at runNextTicks (internal/process/next_tick.js:51:3)
        at processImmediate (timers.js:611:7)
```

**Comment by tinchoz49** [comment]
We should enqueue (or ignore) incoming messages until the handshake of each plugin is completed

**Comment by tinchoz49** [comment]
I was wrong, we cannot do that, messages are the way for extensions to talk.

**Comment by tinchoz49** [comment]
new version released with a initHandler that it waits for both peers to be initialized, best placed to define initialization variables. Updated replicator too.
